title: Stack Problems
description: My Personal Stack Problems
author: Xander
github: https://github.com/cherubic
about: I'm Programmer.
disqus_shortname: stackproblems
google_analytics: G-02ZMEHPSL5

enableTags: true
tagarray: ["python"]

collections: {}

social:
    - icon: fa-github
      link: "https://github.com/cherubic"
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "#"
    # - icon: fa-linkedin
    #   link: "#"
    # - icon: fa-stack-exchange
    #   link: "#"

share: {}
  # twitter_username: github.io
  # fb_appid: 1749788565247320

urls:
    - text: Category
      url: /category/
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://cherubic.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
